generatorName: scalaz
typeMappings:
  AnyType: Json
additionalProperties:
  modelPackage: ssm.model.generated
  apiPackage: ssm.api.generated
  invokerPackage: ssm.api.generated
  artifactId: ssm-client
  serializableModel: "true"
  dateLibrary: java8
templateDir: templates/scala-client
files:
  build.sbt.mustache:
    destinationFilename: build.sbt
  plugins.sbt.mustache:
    destinationFilename: project/plugins.sbt
  build.properties.mustache:
    destinationFilename: project/build.properties
  model.mustache:
    templateType: Model
    destinationFilename: .scala
  api.mustache:
    templateType: API
    destinationFilename: .scala
  dateTimeCodecs.mustache:
    # NOTE This one is used by the models for JSON encoding.
    destinationFilename: src/main/scala/ssm/model/generated/DateTimeCodecs.scala
  HelperCodecs.mustache:
    destinationFilename: src/main/scala/ssm/api/generated/HelperCodecs.scala
  QueryParamTypeclass.mustache:
    destinationFilename: src/main/scala/ssm/api/generated/QueryParamTypeclass.scala
