name: CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate the OpenAPI spec.
      uses: kpurdon/openapi-generator-action@v0.0.3
      with:
        args: validate -i openapi.yml --recommend

  generate_scala_client:
    needs: validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate the Scala client
      uses: kpurdon/openapi-generator-action@v0.0.3
      with:
        args: generate -i openapi.yml -o scala-client -c scala-client-config.yml

    - name: Avoid file ownership issues down the line.
      run: |
        USER=$(id -u)
        GROUP=$(id -g)
        sudo chown -R $USER:$GROUP scala-client

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17

    - name: Enable Coursier cache
      uses: coursier/cache-action@v6

    - name: Install Coursier & SBT
      uses: coursier/setup-action@v1

    - name: Build the client
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cd scala-client && sbt publishLocal

    - name: Save client artifact
      uses: actions/upload-artifact@v3
      with:
        name: scala-client
        path: ~/.ivy2/local/ssm-client/
